services:
  - type: web
    name: trip-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn trip_tracker_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: trip_tracker_project.settings
      - key: PYTHON_VERSION
        value: 3.11
    envVars:
       - key: SECRET_KEY
         value: bk8k3p2^!81s+_5!4wvl0-r*o%rbfltn(5^yoz1y0e2rtdb@j!
       - key: DEBUG
         value: False
       - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
