services:
  - type: web
    name: trip-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn trip_tracker_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: trip_tracker_project.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        value:'django-insecure-=%nx+-g#1)f^8z3-$m&3o4srn9hn+_f^6d@o2%39r=p^n5nr7e'
      - key: DEBUG
        value: True
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
